from base import BranchBaseTest
from tap_tester.base_suite_tests.all_fields_test import AllFieldsTest


class BranchAllFields(AllFieldsTest, BranchBaseTest):
    """Ensure running the tap with all streams and fields selected results in
    the replication of all fields."""
    MISSING_FIELDS = {
        # These fields don't appear in the API response
        "deeplink": [
            'alias',
            'stage',
            'tags',
            'duration'
        ],

        "app_config": [
            'dev_phone_number'
        ],

        "eo_click": [
            'datasource',
            'install_activity_timestamp',
            'last_cta_view_data_tilde_technology_partner',
            'last_cta_view_data_tilde_sub_site_name',
            'last_cta_view_data_tilde_campaign_id',
            'user_data_idfv',
            'user_data_cpp_level',
            'user_data_build',
            'last_attributed_touch_data_tilde_advertising_partner_id',
            'install_activity_touch_data_tilde_channel',
            'last_cta_view_data_tilde_keyword',
            'last_cta_view_data_dollar_meta_is_mobile_data_terms_signed',
            'event_data_exchange_rate',
            'last_cta_view_data_tilde_secondary_publisher',
            'user_data_cpu_type',
            'last_cta_view_data_tilde_feature',
            'user_data_opted_in_status',
            'last_cta_view_data_tilde_tune_publisher_sub2',
            'deep_linked',
            'last_attributed_touch_data_plus_web_format',
            'last_cta_view_data_tilde_tags',
            'store_install_begin_timestamp',
            'content_items',
            'user_data_idfa',
            'event_data_shipping',
            'last_cta_view_data_tilde_customer_placement',
            'last_cta_view_data_tilde_optimization_model',
            'last_attributed_touch_data_tilde_view_id',
            'last_attributed_touch_type',
            'last_attributed_touch_data_tilde_advertising_partner_name',
            'user_data_referral_source',
            'webhook_response_code',
            'last_attributed_touch_data_tilde_organic_search_url',
            'last_attributed_touch_data_tilde_customer_placement',
            'existing_user',
            'user_data_app_store',
            'user_data_windows_aid',
            'user_data_screen_height',
            'last_cta_view_data_tilde_customer_keyword',
            'last_attributed_touch_data_tilde_journey_id',
            'last_cta_view_data_plus_referring_domain',
            'event_data_transaction_id',
            'last_cta_view_data_custom_fields',
            'last_cta_view_data_dollar_3p',
            'last_attributed_touch_data_tilde_secondary_publisher',
            'event_data_tax',
            'user_data_kindle_id',
            'last_cta_view_timestamp',
            'user_data_oaid',
            'event_data_description',
            'event_data_custom_param_10',
            'user_data_is_jailbroken',
            'last_attributed_touch_data_tilde_tune_publisher_sub2',
            'days_from_last_attributed_touch_to_event',
            'last_attributed_touch_data_tilde_customer_campaign',
            'install_activity_touch_data_tilde_feature',
            'last_cta_view_data_tilde_creative_id',
            'user_data_geo_postal_code',
            'last_attributed_touch_data_tilde_customer_ad_set_name',
            'referrer_click_timestamp',
            'user_data_carrier_name',
            'last_attributed_touch_data_tilde_tune_publisher_sub4',
            'seconds_from_last_attributed_touch_to_event',
            'last_cta_view_data_tilde_banner_dimensions',
            'last_cta_view_data_tilde_customer_ad_set_name',
            'user_data_cross_platform_id',
            'last_cta_view_data_tilde_campaign_type',
            'minutes_from_last_attributed_touch_to_event',
            'custom_data',
            'last_attributed_touch_data_dollar_meta_is_mobile_data_terms_signed',
            'last_attributed_touch_data_tilde_tune_publisher_sub5',
            'attributed',
            'last_attributed_touch_data_tilde_journey_name',
            'days_from_install_to_opt_in',
            'user_data_os_version_android',
            'last_attributed_touch_data_tilde_content_id',
            'last_cta_view_data_tilde_customer_secondary_publisher',
            'last_cta_view_data_tilde_ad_set_id',
            'last_attributed_touch_data_tilde_branch_ad_format',
            'user_data_tune_mat_id',
            'last_attributed_touch_data_tilde_ad_name',
            'tune_site_name',
            'event_data_custom_param_6',
            'last_attributed_touch_data_tilde_tune_publisher_sub1',
            'user_data_aaid',
            'last_attributed_touch_data_tilde_campaign_id',
            'last_cta_view_data_tilde_customer_ad_name',
            'last_attributed_touch_data_tilde_placement',
            'event_data_custom_param_4',
            'last_attributed_touch_data_tilde_customer_sub_site_name',
            'last_cta_view_data_tilde_tune_publisher_sub4',
            'user_data_limit_ad_tracking',
            'event_data_custom_param_3',
            'last_attributed_touch_data_tilde_technology_partner',
            'organization_id',
            'last_attributed_touch_data_tilde_customer_keyword',
            'last_attributed_touch_data_tilde_customer_secondary_publisher',
            'user_data_installer_package_name',
            'last_cta_view_data_tilde_tune_publisher_sub3',
            'last_attributed_touch_data_tilde_placement_id',
            'last_cta_view_data_tilde_placement',
            'last_cta_view_data_tilde_tune_publisher_sub1',
            'last_attributed_touch_data_tilde_ad_set_id',
            'last_cta_view_data_tilde_agency_id',
            'last_attributed_touch_data_tilde_keyword',
            'event_data_custom_param_5',
            'last_attributed_touch_data_tilde_tune_publisher_sub3',
            'last_cta_view_data_tilde_branch_ad_format',
            'last_cta_view_data_tilde_agency',
            'last_cta_view_data_tilde_tune_publisher_id',
            'webhook_request_url',
            'last_attributed_touch_data_tilde_tune_publisher_name',
            'user_data_developer_identity',
            'last_cta_view_data_plus_web_format',
            'install_activity_touch_data_dollar_meta_is_mobile_data_terms_signed',
            'last_cta_view_data_tilde_external_touch_id',
            'last_cta_view_data_tilde_journey_name',
            'last_attributed_touch_data_tilde_external_touch_id',
            'match_guaranteed',
            'customer_event_alias',
            'last_attributed_touch_data_tilde_view_name',
            'event_data_custom_param_2',
            'last_cta_view_data_tilde_advertising_partner_id',
            'last_attributed_touch_data_tilde_agency',
            'last_attributed_touch_data_tilde_ad_id',
            'last_attributed_touch_data_dollar_fb_data_terms_not_signed',
            'install_activity_touch_data_tilde_campaign',
            'last_cta_view_data_tilde_keyword_id',
            'last_cta_view_data_tilde_creative_name',
            'user_data_app_version',
            'reengagement_activity_touch_data_dollar_meta_is_mobile_data_terms_signed',
            'last_attributed_touch_data_tilde_keyword_id',
            'last_attributed_touch_data_dollar_3p',
            'last_attributed_touch_data_tilde_sub_site_name',
            'last_attributed_touch_data_tilde_keyword_match_type',
            'last_cta_view_data_tilde_advertising_partner_name',
            'event_data_coupon',
            'event_data_custom_param_9',
            'event_data_search_query',
            'last_cta_view_data_plus_via_features',
            'last_attributed_touch_data_tilde_customer_ad_name',
            'last_cta_view_data_tilde_tune_publisher_sub5',
            'event_data_custom_param_8',
            'webhook_request_headers',
            'last_cta_view_data_tilde_tune_publisher_name',
            'last_attributed_touch_data_tilde_stage',
            'event_data_custom_param_7',
            'last_cta_view_data_tilde_customer_campaign',
            'user_data_app_package_name',
            'last_attributed_touch_data_tilde_secondary_ad_format',
            'user_data_internet_connection_type',
            'hours_from_last_attributed_touch_to_event',
            'event_data_ad_type',
            'last_cta_view_data_tilde_campaign',
            'last_cta_view_data_tilde_stage',
            'last_attributed_touch_data_plus_touch_id',
            'event_data_affiliation',
            'last_cta_view_data_tilde_ad_name',
            'last_cta_view_data_tilde_ad_set_name',
            'last_attributed_touch_data_tilde_optimization_model',
            'last_attributed_touch_data_tilde_secondary_publisher_id',
            'user_data_http_referrer',
            'last_cta_view_data_tilde_id',
            'last_attributed_touch_data_tilde_campaign_type',
            'last_cta_view_data_tilde_secondary_publisher_id',
            'last_cta_view_data_tilde_secondary_ad_format',
            'user_data_screen_width',
            'last_attributed_touch_data_tilde_ad_set_name',
            'last_cta_view_data_plus_touch_id',
            'last_cta_view_data_tilde_view_id',
            'first_event_for_user',
            'last_attributed_touch_data_tilde_banner_dimensions',
            'last_attributed_touch_timestamp',
            'last_cta_view_data_tilde_journey_id',
            'last_cta_view_data_tilde_customer_sub_site_name',
            'organization_name',
            'user_data_android_id',
            'last_cta_view_data_tilde_placement_id',
            'tune_site_id',
            'persona_identifiers',
            'last_cta_view_data_tilde_ad_id',
            'last_cta_view_data_tilde_view_name',
            'last_cta_view_data_tilde_channel',
            'event_data_custom_param_1',
            'last_attributed_touch_data_tilde_creative_id',
            'last_attributed_touch_data_tilde_agency_id'
        ]
    }

    @staticmethod
    def name():
        return "tap_tester_branch_all_fields_test"

    def streams_to_test(self):
        streams_to_exclude = self.streams_with_no_data()

        return self.expected_stream_names().difference(streams_to_exclude)
